### ISSUE TITLE
maybe @types/react @types/react-dom should in devDependencies not dependencies

### ISSUE THREAD

**Issue by leavesster** [davinchee/react-typescript-boilerplate#1]
https://github.com/davinchee/react-typescript-boilerplate/blob/3a7473b708f210f8749c0b8b6684bb7d2d2bac59/package.json#L42

Thank you for your article, but maybe the `@types/react` `@types/react-dom` should in `devDependecies` ?

**Comment by 0xdavinchee** [comment]
You are right, it makes more sense to keep `@types/` in devDependencies!
